### PR TITLE
Kotlin upgrade fix

### PR DESCRIPTION
**Pull request by james-cobb**
These look to me to be the only changes needed to fix the kotlin version upgrade.

### CODE REVIEW

**Comment by orjan** [comment]
I'm not sure why the feedback from travis is not working, but it looks like the build is failing: https://travis-ci.org/AsynkronIT/protoactor-kotlin/builds/509961232

**Comment by james-cobb** [comment]
There was another dependency that was missing, and then finally the intermittent test failed again, so I've cherry picked the fix from #44 and added to this PR.

Now this is passing -  I think it's the minimal patch to get master branch working again.

**Comment by Globegitter** [comment]
@rogeralsing would also be great to get this PR merged if nothing is blocking it anymore.

**Comment by guenhter** [comment]
@james-cobb could you resolve the conflicts

**Comment by james-cobb** [comment]
@guenhter Yes I'll resolve the conflicts so we can merge this too. On vacation but will find some time when I can... :)

**Comment by james-cobb** [comment]
@guenhter conflicts resolved now. This is now a pretty simple diff and gets master building with all tests passing with the new coroutines API. @rogeralsing would be great to get this PR merged now.

**Comment by guenhter** [comment]
@james-cobb cool. Maybe you squash some of the commits. 9 commits seems like a little bit overkill for the changes done here, doesn't it?

**Comment by james-cobb** [comment]
@guenhter that's a good call. I've squashed down to one commit for the original changes, and one for merging master to sort the conflicts.

**Comment by guenhter** [comment]
@rogeralsing Thx for the invite to the organization. It seems that I have now right e.g. to merge in the `protoactor-go` but in the `protoactor-kotlin` I can't to anything developer related...
Was your intention when gave us developer rights to support you on merging requests and having an eye on issues? If so, maybe you could have a second look over the kotlin project right. Thx

**Comment by rogeralsing** [comment]
It was an oversight on my side, I added the Kotlin repo to the developers team now. this should fix the issue :-)

**Comment by guenhter** [comment]
Interestingly, it's still not possible for me to merge e.g. this merge request...

**Comment by guenhter** [comment]
Nice. Now it works. Thx

**Pull request merged**
