### PR TITLE
Upgrade gradle to 5.5.1

### PR DESCRIPTION
**Pull request by guenhter**
* Upgrade gradle to most recent version
* use openjdk instead of oraclejdk to fix the travis build
* update some dependencies

### CODE REVIEW

**Comment by james-cobb** [comment]
@guenhter We have quite a few dependency versions (eg protobuf) repeated in multiple modules. Is it possible to extract the versions as a constant in the root build file so it's not repeated? And if there are any dependencies needed in all modules they could be declared in the root build.

I'll find some time to update our project that uses proto-actor to use this branch, and check if there are any problems updating versions.

**Comment by guenhter** [comment]
Good catch. I'll do that.

**Comment by guenhter** [comment]
> I'll find some time to update our project that uses proto-actor to use this branch, and check if there are any problems updating versions.

I guess when a new release of this protoactor-kotlin is published (0.0.3) it will definitly break some users, because the current latest release 0.0.2 uses very outdated dependencies of e.g. coroutines when they were not yet stable. Now we use the stable version 1.x...

**Comment by guenhter** [comment]
> We have quite a few dependency versions (eg protobuf) repeated in multiple modules. Is it possible to extract the versions as a constant in the root build file so it's not repeated? And if there are any dependencies needed in all modules they could be declared in the root build.

@james-cobb done.

**Comment by james-cobb** [comment]
Thanks for pulling out the versions as constants. Looks good.

I've never looked closely at all the build files and dependencies. But your work tidying all this up has got me thinking about it properly. So I'm afraid I've got another couple of questions now !!

I read up on the difference between api and implementation - is there good reason for the api declarations we have? Do they all need to be exposed to applications that use the library?

And a few dependencies weren't the very latest version - maybe a good reason, or in at least one case just a very recent (last few days) release:

nebula-bintray-plugin is on 7.3.0 - we depend on 6.0.6
slf4j is on 1.7.28  - we depend on 1.7.26 (very recent releases)
kotlin logging is on 1.7.4 - we depend on 1.7.3

Otherwise I think the PR is good to merge.

I've used this branch in our main project, and the only changes needed were for the coroutine api changes - nothing else unexpected broke.

I did discover that there's a library API change introduced in the December 2018 commits that I can do a quick PR for before we go for a new release.

**Comment by guenhter** [comment]
> Do they all need to be exposed to applications that use the library?

I guess most of them are correct as they are. API should be e.g. used, when a class of a dependency is used not only internally but is exposed. When all the classes of a dependency are just used internally, then `implementation` is the right one.

> nebula-bintray-plugin is on 7.3.0 - we depend on 6.0.6

Lot of things have changed here. I guess this would be worth its own pull request...

> slf4j is on 1.7.28 - we depend on 1.7.26 (very recent releases)
    kotlin logging is on 1.7.4 - we depend on 1.7.3

True, but such patch versions change every day. I'll update them next time when I check for dependency updates.

**Comment by james-cobb** [comment]
Thanks for the responses @guenhter - I think we should merge this PR.  @orjan do you want to review, or should I merge?

**Comment by james-cobb** [comment]
(once we've merged this - I'm working on a PR to revert the DefaultDispatcher API to the way it was, and also hopefully remove use of GlobalScope that was introduced updating the coroutine APIs. If possible I'd like to do that before we release 0.0.3)

**Comment by james-cobb** [comment]
@guenhter You requested a review from Orjan - are you happy for this PR to be merged without his review?

**Comment by guenhter** [comment]
I have no problem with that, as long a second pair of eyes looked over it.

**Comment by james-cobb** [comment]
Well, may not be worth much, but I looked over it in detail ;)

**Pull request merged**
