### PR TITLE
Upgrade to gradle 5.3.1 + some minor refactorings

### PR DESCRIPTION
**Pull request by guenhter**
One commit does the upgrade to gradle 5.1.1. The commit also aligns all the configurations to `api` and `implementation` instead of `compile` and switches to the `java-library` plugin instead of `java`.

Furthermore, one test is fixed, which sporadically fails with gradle. For that, the new test dependency to `Awaitility` was introduced (great tool for async assertions).

The last commit only does some reformating of the Kotlin code.

### CODE REVIEW

**Comment by guenhter** [comment]
Any thoughts on this? Can this be merged?

**Comment by guenhter** [comment]
Also did some upgrades of most of the libraries (including Kotlin) in the last commit.

**Comment by Globegitter** [comment]
@orjan @rogeralsing  anything blocking this PR from getting merged in?

**Comment by james-cobb** [comment]
Definitely need to either merge this PR, and then fix some conflicts on #47 and merge that, or the other way round. At the moment we have a failing build on the master branch.

**Comment by Globegitter** [comment]
@rogeralsing another friendly ping, or @PotterDai @yangdiangzb @Valentin-Miroshnichenko does one of you have commit rights to this repo and would feel comfortable in aiding to get these two PRs merged in to make this library usable again with kotlin?

**Comment by rogeralsing** [comment]
@Globegitter I've sent an invite to join the dev team

**Comment by Globegitter** [comment]
@rogeralsing thanks for the invite, we are still evaluating a few different options including protoactor, but I really like this project so far as I am quite familiar with protobufs. Also happy to make sure the other PR gets merged in :)

**Pull request merged**
